triggers:
- envs: []
  last_enabled_at: 2024-04-14 09:34:08.862877
  name: load bucket to bq
  pipeline_uuid: gcsbucket_to_bigquery
  schedule_interval: 15 6 * * *
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-04-15 06:15:00
  status: active
  variables: {}
