triggers:
- envs: []
  last_enabled_at: 2024-04-14 09:32:56.411742
  name: Daily 6am
  pipeline_uuid: load_2021q1_greentripdata_to_gcp
  schedule_interval: 0 6 * * *
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-04-15 06:00:00
  status: active
  variables: {}
